package com.redhat.poc.banking.slamgmtrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BatchJobInfo implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Transaction Type")
   private java.lang.String transactionType;
   @org.kie.api.definition.type.Label(value = "Total Transactions")
   private java.lang.Integer totalTransactions;
   @org.kie.api.definition.type.Label(value = "Number Of Transactions Processed")
   private java.lang.Integer noOfTransProcessed;
   @org.kie.api.definition.type.Label(value = "Percent Of Transactions Complete")
   private java.lang.Double pctTransComplete;

   public BatchJobInfo()
   {
   }

   public java.lang.String getTransactionType()
   {
      return this.transactionType;
   }

   public void setTransactionType(java.lang.String transactionType)
   {
      this.transactionType = transactionType;
   }

   public java.lang.Integer getTotalTransactions()
   {
      return this.totalTransactions;
   }

   public void setTotalTransactions(java.lang.Integer totalTransactions)
   {
      this.totalTransactions = totalTransactions;
   }

   public java.lang.Integer getNoOfTransProcessed()
   {
      return this.noOfTransProcessed;
   }

   public void setNoOfTransProcessed(java.lang.Integer noOfTransProcessed)
   {
      this.noOfTransProcessed = noOfTransProcessed;
   }

   public java.lang.Double getPctTransComplete()
   {
      return this.pctTransComplete;
   }

   public void setPctTransComplete(java.lang.Double pctTransComplete)
   {
      this.pctTransComplete = pctTransComplete;
   }

   public BatchJobInfo(java.lang.String transactionType,
         java.lang.Integer totalTransactions,
         java.lang.Integer noOfTransProcessed,
         java.lang.Double pctTransComplete)
   {
      this.transactionType = transactionType;
      this.totalTransactions = totalTransactions;
      this.noOfTransProcessed = noOfTransProcessed;
      this.pctTransComplete = pctTransComplete;
   }

}