package com.redhat.poc.banking.slamgmtrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SLACriteria implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "TransactionType")
   private java.lang.String transactionType;
   @org.kie.api.definition.type.Label(value = "Percentage")
   private java.lang.Double percentage;
   @org.kie.api.definition.type.Label(value = "Type")
   private java.lang.String type;

   public SLACriteria()
   {
   }

   public java.lang.String getTransactionType()
   {
      return this.transactionType;
   }

   public void setTransactionType(java.lang.String transactionType)
   {
      this.transactionType = transactionType;
   }

   public java.lang.Double getPercentage()
   {
      return this.percentage;
   }

   public void setPercentage(java.lang.Double percentage)
   {
      this.percentage = percentage;
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public SLACriteria(java.lang.String transactionType,
         java.lang.Double percentage, java.lang.String type)
   {
      this.transactionType = transactionType;
      this.percentage = percentage;
      this.type = type;
   }

}