package com.redhat.poc.banking.slamgmtrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SLAMessage implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Transaction Type")
   private java.lang.String transactionType;
   @org.kie.api.definition.type.Label("Message")
   private java.lang.String message;

   public SLAMessage()
   {
   }

   public java.lang.String getTransactionType()
   {
      return this.transactionType;
   }

   public void setTransactionType(java.lang.String transactionType)
   {
      this.transactionType = transactionType;
   }

   public java.lang.String getMessage()
   {
      return this.message;
   }

   public void setMessage(java.lang.String message)
   {
      this.message = message;
   }

   public SLAMessage(java.lang.String transactionType, java.lang.String message)
   {
      this.transactionType = transactionType;
      this.message = message;
   }

}