package com.redhat.poc.banking.slamgmtrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SLAWarn implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Transaction Type")
   private java.lang.String transactionType;
   @org.kie.api.definition.type.Label(value = "Message")
   private java.lang.String message;

   public SLAWarn()
   {
   }

   public java.lang.String getTransactionType()
   {
      return this.transactionType;
   }

   public void setTransactionType(java.lang.String transactionType)
   {
      this.transactionType = transactionType;
   }

   public java.lang.String getMessage()
   {
      return this.message;
   }

   public void setMessage(java.lang.String message)
   {
      this.message = message;
   }

   public SLAWarn(java.lang.String transactionType, java.lang.String message)
   {
      this.transactionType = transactionType;
      this.message = message;
   }

}